application: epigrass-hrd
version: 2
runtime: python27
api_version: 1
threadsafe: true

# In production, uncomment line below.
#default_expiration: "30d"

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?test$
- ^(.*/)?test$
- ^Makefile
- ^COPYING.LESSER
- ^README.md
- \.gitignore
- ^\.git/.*
- \.*\.lint$

builtins:
- appstats: on #/_ah/stats/
- remote_api: on #/_ah/remote_api/

handlers:
- url: /admin/.*
  script: main.app
  login: admin

- url: /favicon\.ico
  mime_type: image/png
  static_files: static/egicon.png
  upload: static/egicon.ico

- url: /apple-touch-icon\.png
  static_files: static/apple-touch-icon.png
  upload: static/apple-touch-icon.png

- url: /apple-touch-icon-precomposed\.png
  static_files: static/apple-touch-icon-precomposed.png
  upload: static/apple-touch-icon-precomposed.png

- url: /(robots\.txt|humans\.txt|crossdomain\.xml)
  static_files: static/\1
  upload: static/(robots\.txt|humans\.txt|crossdomain\.xml)

- url: /epigrass/css
  mime_type: text/css
  static_dir: epigrass/static/css

- url: /epigrass/js
  mime_type: text/javascript
  static_dir: epigrass/static/js

- url: /epigrass/img/(.*\.(gif|png|jpg))
  static_files: epigrass/static/img/\1
  upload: epigrass/static/img/(.*\.(gif|png|jpg))

- url: /css
  mime_type: text/css
  static_dir: static/css

- url: /js
  mime_type: text/javascript
  static_dir: static/js

- url: /img/(.*\.(gif|png|jpg))
  static_files: static/img/\1
  upload: static/img/(.*\.(gif|png|jpg))

- url: /.*
  script: main.app
#  secure: always

libraries:
- name: jinja2
  version: "2.6"
- name: webapp2
  version: "2.5.1"
- name: markupsafe
  version: "0.15"
- name: pycrypto
  version: "2.6"

error_handlers:
  # Only errors with error_code, don't put a default error here
  - error_code: over_quota
    file: epigrass/templates/errors/over_quota.html

  - error_code: dos_api_denial
    file: epigrass/templates/errors/dos_api_denial.html

  - error_code: timeout
    file: epigrass/templates/errors/timeout.html
